name: Build (ROS 2 Jazzy)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04  # Jazzy is tier-1 on Ubuntu 24.04
    steps:
      - uses: actions/checkout@v4

      # Install ROS 2 Jazzy
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      # Install package dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      # Build the workspace
      - name: Build
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --symlink-install
