name: CI (ROS 2 build & test)
on:
  push: { branches: [ main ] }
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Test (ROS 2 Jazzy)
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: jazzy
          package-name: gazebot_ros
          colcon-defaults: |
            { "build": { "symlink-install": true } }
